import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size: 50px;
          color:red;
        }
        h3{
          font-size: 30px;
        }

        `}
      </style>
      <Head>
        <title>Hunting Coder </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='myspn'> Hunting Coder</span>
        </h1>
        <div class={styles.img_wrp}>
        <Image className={styles.myimg} src='/coder.jpg' width={237} height={158}/>
        </div>

        <p className={styles.description}>
          A Blog by testing coder
        </p>
        <div class="blog">
        <h2>Populer Blogs</h2>
          <div class="blogItem">
            <h3>How to learn javascript</h3>
            <p>its a langwage for website</p>
          </div>
          <div class="blogItem">
            <h3>How to learn javascript</h3>
            <p>its a langwage for website</p>
          </div>
          <div class="blogItem">
            <h3>How to learn javascript</h3>
            <p>its a langwage for website</p>
          </div>
          <div class="blogItem">
            <h3>How to learn javascript</h3>
            <p>its a langwage for website</p>
          </div>
        </div>

      </main>

    </div>
  )
}
